services:
  - type: web
    name: background-removal-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    runtime: python3
    autoDeploy: true